name: Manual Compile given target.
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Target to build'
        required: true


jobs:
  build:
    name: Build - ${{ matrix.platform.release_for }}
    runs-on: ubuntu-latest
    steps:
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ github.event.inputs.name }}
          args: "--release"
          strip: true
