name: Manual Compile given target.
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Target to build'
        required: true
      toolchain:
        description: |
          The target toolchain to use (one of "stable", "beta", or "nightly").
        default: stable


jobs:
  build:
    name: Build - ${{ matrix.platform.release_for }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ github.event.inputs.name }}
          toolchain: ${{ github.event.inputs.toolchain }}
          args: "--release"
          strip: true
