name: Manual Compile given target.
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Target to build'
        required: true
      toolchain:
        description: |
          The target toolchain to use (one of "stable", "beta", or "nightly").
        default: stable
      args:
        description: |
          The arguments to be passed to cross or cargo when building, as a
          space-separated string.
        default: ""


jobs:
  build:
    name: Build - ${{ github.event.inputs.name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ github.event.inputs.name }}
          toolchain: ${{ github.event.inputs.toolchain }}
          args: ${{ github.event.inputs.args }}
          strip: true
