name: Build Beihang-Login for multiple platforms

on:
  push:
    tags:
      - v**

jobs:
  release:
    name: Release - ${{ matrix.platform.os_name }}
    strategy:
      matrix:
        platform:
          - os_name: Linux-x86_64-musl
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - os_name: Linux-ARM64-musl
            os: ubuntu-latest
            target: aarch64-unknown-linux-musl

          - os_name: Linux-Armv7-musl
            os: ubuntu-latest
            target: armv7-unknown-linux-musleabihf

          - os_name: Linux-MIPS-musl
            os: ubuntu-latest
            target: mipsel-unknown-linux-musl
            toolchain: nightly

          - os_name: Windows-x86_64-msvc
            os: windows-latest
            target: x86_64-pc-windows-msvc

          - os_name: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin

          - os_name: macOS-apple
            os: macOS-latest
            target: aarch64-apple-darwin

#          - os_name: Windows-i686-mscv
#            os: windows-latest
#            target: i686-pc-windows-msvc


    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.platform.toolchain }}
          args: "--release"
          strip: true
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: buaa-login
          target: ${{ matrix.platform.target }}
        if: matrix.toolchain == 'stable'